-- AlterTable
ALTER TABLE "User" ALTER COLUMN "exp" SET DEFAULT 0,
ALTER COLUMN "balance_coin" SET DEFAULT 0,
ALTER COLUMN "cigarettes_avoided" SET DEFAULT 0,
ALTER COLUMN "city" DROP NOT NULL,
ALTER COLUMN "is_premium" SET DEFAULT false,
ALTER COLUMN "money_saved" SET DEFAULT 0.0,
ALTER COLUMN "province" DROP NOT NULL,
ALTER COLUMN "relapse_quota" SET DEFAULT 0,
ALTER COLUMN "streak_count" SET DEFAULT 0,
ALTER COLUMN "time_zone" DROP NOT NULL,
ALTER COLUMN "username" DROP NOT NULL;
