name: Build and Deploy to Cloud Run

on:
  push:
    branches: ["main"]

env:
  PROJECT_ID: bangkit-capstone-424110 # TODO: update Google Cloud project id
  GAR_LOCATION: asia-southeast2 # TODO: update Artifact Registry location
  GAR_REPOSITORY_NAME: be-unsmoke # TODO: update Artifact Registry Repository name
  SERVICE: be-unsmoke # TODO: update Cloud Run service name
  REGION: asia-southeast2 # TODO: update Cloud Run service region
  INSTANCE_CONNECTION_NAME: bangkit-capstone-424110:asia-southeast2:bangkit-capstone
  DATABASE_URL: postgresql://bangkit-capstone:root@localhost:5432/unsmoke
  PORT: 8080

jobs:
  deploy:
    permissions:
      contents: "read"
      id-token: "write"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}"

      - name: Configure Docker to use gcloud
        run: |-
          gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev --quiet

      - name: Build and Push Container
        run: |-     
          docker build \
            --build-arg INSTANCE_CONNECTION_NAME="${{ env.INSTANCE_CONNECTION_NAME }}" \
            --build-arg DATABASE_URL="${{ env.DATABASE_URL }}" \
            --build-arg PORT="${{ env.PORT }}" \
            -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPOSITORY_NAME }}/${{ env.SERVICE }}:${{ github.sha }}" ./
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPOSITORY_NAME }}/${{ env.SERVICE }}:${{ github.sha }}"
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPOSITORY_NAME }}/${{ env.SERVICE }}:${{ github.sha }}
          env_vars: INSTANCE_CONNECTION_NAME=${{ env.INSTANCE_CONNECTION_NAME }},DATABASE_URL=${{ env.DATABASE_URL }}

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
