name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main
      - dev

env:
  PROJECT_ID: bangkit-capstone-424110 # TODO: update Google Cloud project id
  GAR_LOCATION: asia-southeast2 # TODO: update Artifact Registry location
  GAR_REPOSITORY_NAME: be-unsmoke # TODO: update Artifact Registry Repository name
  SERVICE: be-unsmoke # TODO: update Cloud Run service name
  REGION: asia-southeast2 # TODO: update Cloud Run service region
  DATABASE_URL: postgresql://bangkit-capstone:root@34.101.46.19:5432/unsmoke

jobs:
  deploy:
    permissions:
      contents: "read"
      id-token: "write"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}"

      - name: Configure Docker to use gcloud
        run: |-
          gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev --quiet

      - name: Set Environment Variables
        id: set-env
        run: |
          if [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            echo "::set-output name=service::${{ env.SERVICE }}-dev"
            echo "::set-output name=tag::dev"
          else
            echo "::set-output name=service::${{ env.SERVICE }}-prod"
            echo "::set-output name=tag::${{ github.sha }}"
          fi

      - name: Build and Push Container
        run: |-     
          docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPOSITORY_NAME }}/${{ steps.set-env.outputs.service }}:${{ steps.set-env.outputs.tag }}" ./
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPOSITORY_NAME }}/${{ steps.set-env.outputs.service }}:${{ steps.set-env.outputs.tag }}"

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ steps.set-env.outputs.service }}
          region: ${{ env.REGION }}
          image: ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.GAR_REPOSITORY_NAME }}/${{ steps.set-env.outputs.service }}:${{ steps.set-env.outputs.tag }}
          env_vars: DATABASE_URL=${{ env.DATABASE_URL }}

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
